source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
def pods

    pod 'PWDataBridge', :path => '../../PWDataBridge'
end
target 'PWDataBridgeSwiftExample' do
    pods
end
